version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
   
  chopstick-ubuntu:
    build:
      dockerfile: build/Dockerfile.chopstick-ubuntu
      context: .
    ports:
      - "8080:8080"
    privileged: true
    environment:
      - REDIS_URL=redis://redis:6379
      - HTTP_ADDR=:8080
    links:
      - redis
