version: "3"

services:
  message-queue:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=gimi
      - POSTGRES_PASSWORD=gimi
      - POSTGRES_DB=gimi

  invoker-linux:
    build:
      dockerfile: build/Dockerfile.invoker-linux
      context: .
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://message-queue:6379
      - HTTP_ADDR=:5001
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    links:
      - message-queue

  runtime-filter:
    build:
      dockerfile: build/Dockerfile.runtime-filter
      context: .
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - REDIS_URL=redis://message-queue:6379
    links:
      - message-queue

  controller:
    build:
      dockerfile: build/Dockerfile.controller
      context: .
    ports:
      - "3000:3000"
    environment:
      - RUNTIME_FILTER_URL=runtime-filter:50051
      - PORT=3000
      - DB_URL=postgres://gimi:gimi@db:5432/gimi
      - DB_SYNC=true
    links:
      - runtime-filter
