version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  invoker-ubuntu:
    build:
      dockerfile: build/Dockerfile.invoker-ubuntu
      context: .
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://redis:6379
      - HTTP_ADDR=:5001
    links:
      - redis

  runtime-filter:
    build:
      dockerfile: build/Dockerfile.runtime-filter
      context: .
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - REDIS_URL=redis://redis:6379
    links:
      - redis

  db-filter:
    build:
      dockerfile: build/Dockerfile.db-filter
      context: .
    ports:
      - "50052:50052"
    environment:
      - PORT=50052
      - DB_URL=postgres://postgres:6379

  controller:
    build:
      dockerfile: build/Dockerfile.controller
      context: .
    ports:
      - "3000:3000"
    environment:
      - RUNTIME_FILTER_URL=runtime-filter:50051
      - PORT=3000
    links:
      - runtime-filter
