version: "3"

services:
  message-queue:
    image: redis
    ports:
      - "6379:6379"

  blacklist-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=blacklist
      - POSTGRES_PASSWORD=blacklist
      - POSTGRES_DB=blacklist

  invoker-linux:
    build:
      dockerfile: build/Dockerfile.invoker-linux
      context: .
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://message-queue:6379
      - HTTP_ADDR=:5001
    links:
      - message-queue

  runtime-filter:
    build:
      dockerfile: build/Dockerfile.runtime-filter
      context: .
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - REDIS_URL=redis://message-queue:6379
    links:
      - message-queue

  db-filter:
    build:
      dockerfile: build/Dockerfile.db-filter
      context: .
    ports:
      - "50052:50052"
    environment:
      - PORT=50052
      - DB_URL=postgres://blacklist:blacklist@blacklist-db:5432/blacklist
    links:
      - blacklist-db

  controller:
    build:
      dockerfile: build/Dockerfile.controller
      context: .
    ports:
      - "3000:3000"
    environment:
      - RUNTIME_FILTER_URL=runtime-filter:50051
      - DB_FILTER_URL=db-filter:50052
      - PORT=3000
    links:
      - runtime-filter
      - db-filter
