name: CI
on:
  pull_request:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules # caching whole node_modules is not recommended since it restricts using different versions of node for the other jobs
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 14.x
      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --pure-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: "main"

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3

  build:
    runs-on: ubuntu-latest
    needs: [prepare, lint]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: "main"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"

      - name: Build affected
        run: npx nx affected --target=build --parallel=3

  test:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: "main"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"

      - run: npx nx affected --target=test --parallel=3
